config/routes.rb
Rails.application.routes.draw do
  
  resources :exercises
  resources :manages
  root "home#index"
  
  resource :homes 
  
  resources :entries do
  	collection do
       get :view_all
  	end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/entry.rb
class Entry < ApplicationRecord
 resourcify
 belongs_to :user
 
 scope :todays_entry, -> { where(created_at: Date.today.all_day) }
 #scope :user_entry, -> {where(user_id: params[:id])}
 

 def day 
    self.created_at.strftime("%b %e, %Y")
 end	

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
     @test = "trying to use rebase" 
     @entries = current_user.entries.todays_entry
  end

  def view_all
    @test = "making conflict"
    @a = "aaaaa"
    @b = "bbbbbbb"
    @entries = current_user.entries.order(created_at: :desc).group_by(&:day)
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = current_user.entries.build(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entries_path, notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entries_path, notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:calories, :proteins, :fats, :user_id)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<div class="card mt-6 has-background-primary-light">
  <div class="card-content">
    <div class="content">
      <h2 class="title">New Entry</h2>

<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="label">
      <%= form.label :calories %>
    </div>
    <div class="control">
      <%= form.number_field :calories , class: "input"%>
    </div>
  </div>

  <div class="field">
    <div class="label">
      <%= form.label :proteins %>
    </div>  
    <div class="control">
      <%= form.number_field :proteins , class: "input"%>
    </div>  
  </div>

  <div class="field">
    <div class="label">
      <%= form.label :fats %>
    </div>
    <div class="control">
      <%= form.number_field :fats , class: "input"%>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-success is-outlined" %>
  </div>
<% end %>
    </div>
  </div>
</div>

app/views/entries/edit.html.erb
<h1 class="title">Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry, class: "button is-dark is-outlined" %> 
<%= link_to 'Back', entries_path, class: "button is-dark is-outlined" %>

app/views/entries/index.html.erb
<div class="columns mt-6 is-centered">
 <% @entries.each do |entry| %>
  <div class="column is-one-quarter">
    <div class="card">
      <header class="card-header">
        <p class="card-header-title is-size-6"> Meal </p>
      </header>
      <div class="card-content">
        <div class="content">  
          <p><span class = "has-text-weight-bold is-size-8"><%= entry.calories %> kcal Calories</p></span>
          <p><span class = "has-text-weight-bold is-size-8"><%= entry.proteins %>g Protein</p></span>
          <p><span class = "has-text-weight-bold is-size-8"><%= entry.fats %>g fats</p></span>
        </div>
      </div>  
     <div class="card-footer">  
      
        <%= link_to 'Show', entry, class: "card-footer-item button is-primary is-small" %>
        <%= link_to 'Edit', edit_entry_path(entry), class: "card-footer-item button is-info is-small" %>
        <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-footer-item button is-danger is-small" %>
      </div>
    </div>
  </div>  
 <% end %>
</div>
<div class="is-vcentered">
<%= link_to 'View all Entries',  view_all_entries_path, class: "button is-success is-outlined" %>
</div>

app/views/entries/new.html.erb
<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path, class: "button is-dark is-outlined" %>

app/views/entries/show.html.erb
<div class="columns mt-6 is-centered">
  <div class="columns is-one-quarter"> 
    <div class="card">
      <header class="card-header">
        <p class="card-header-title is-size-4"> Meal </p>
      </header>
      <div class="card-content">
        <div class="content">  
          <p><span class = "has-text-weight-bold is-size-6"><%= @entry.calories %> kcal Calories</p></span>
          <p><span class = "has-text-weight-bold is-size-6"><%= @entry.proteins %>g Protein</p></span>
          <p><span class = "has-text-weight-bold is-size-6"><%= @entry.fats %>g fats</p></span>
        </div>
      </div>  
    <div class="card-footer">  
      <div class="card-footer-item"> 
        <%= link_to 'Edit', edit_entry_path(@entry), class: "button is-info" %>
      </div>
      <div class="card-footer-item">  
        <%= link_to 'Back', entries_path, class: "button is-primary" %>
      </div>  
      </div>
    </div>
  </div>  
 </div>
</div>

app/views/entries/view_all.html.erb
<div class="columns mt-6">
 <% @entries.each do |day, entries| %>
  <div class="column">
  	<header class="is-size-4">Entry for <%= day %></header>
  	<nav class="level is-mobile">
        		<div class="level-item has-text-centered">
        			<div>
        				<div class="level-item"><p class="subtitle">Total Calories  : </p>
        				<p class="subtitle"><%= entries.pluck(:calories).sum %> grams </p></div>
        				<div class="level-item"><p class="subtitle">Total Proteins  : </p>
        				<p class="subtitle"><%= entries.pluck(:proteins).sum %> grams</p></div>
        				<div class="level-item"><p class="subtitle">Total Fats : </p>
        				<p class="subtitle"><%= entries.pluck(:fats).sum %> grams</p></div>
        			</div>
        		</div>
      </nav>
  	<% entries.each do |entry| %>
    <div class="card">
      <header class="card-header">
        <p class="card-header-title is-size-6"> Meal </p>
      </header>
      <div class="card-content">
        <div class="content">  
          <p><span class = "has-text-weight-bold is-size-8"><%= entry.calories %> kcal Calories</p></span>
          <p><span class = "has-text-weight-bold is-size-8"><%= entry.proteins %>g Protein</p></span>
          <p><span class = "has-text-weight-bold is-size-8"><%= entry.fats %>g fats</p></span>
        </div>
      </div>  
     <% end %>
    </div>
  </div>  
</div>
 <% end %>
</div>