config/routes.rb
Rails.application.routes.draw do
  
  resources :exercises
  resources :manages
  root "home#index"
  
  resource :homes 
  
  resources :entries do
  	collection do
       get :view_all
  	end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/manage.rb
class Manage < ApplicationRecord

  scope :only_users, -> {joins(:roles).where.not('roles.name = ?', "admin")}
  scope :desc, -> {order(created_at: :desc)}

end

app/controllers/manages_controller.rb
class ManagesController < ApplicationController
  before_action :set_manage, only: %i[ show edit update destroy ]

  # GET /manages or /manages.json
  def index
    @manage = User.joins(:roles).where.not('roles.name = ?', "admin")
  end

  # GET /manages/1 or /manages/1.json
  def show
    @user = User.find(params[:id])
    @entries = Entry.where(user_id: params[:id]).order(created_at: :desc).group_by(&:day)
  end

  # GET /manages/new
  def new
    @manage = User.new
  end

  # GET /manages/1/edit
  def edit
  end

  # POST /manages or /manages.json
  def create
    @manage = User.new(manage_params)

    respond_to do |format|
      if @manage.save
        format.html { redirect_to @manage, notice: "Manage was successfully created." }
        format.json { render :show, status: :created, location: @manage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @manage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manages/1 or /manages/1.json
  def update
    respond_to do |format|
      if @manage.update(manage_params)
        format.html { redirect_to @manage, notice: "Manage was successfully updated." }
        format.json { render :show, status: :ok, location: @manage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @manage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manages/1 or /manages/1.json
  def destroy
    @manage.destroy
    respond_to do |format|
      format.html { redirect_to manages_url, notice: "Manage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manage
      @manage = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def manage_params
      params.require(:user).permit(:name, :id, :email)
    end
end

app/helpers/manages_helper.rb
module ManagesHelper
end

app/views/manages/_form.html.erb
<%= form_with(model: manage, local: true) do |form| %>
  <% if manage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manage.errors.count, "error") %> prohibited this manage from being saved:</h2>

      <ul>
      <% manage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/manages/edit.html.erb
<h1>Editing Manage</h1>

<%= render 'form', manage: @manage %>

<%= link_to 'Show', @manage %> |
<%= link_to 'Back', manages_path %>

app/views/manages/index.html.erb
<div class="columns mt-6 is-centered">
 <% @manage.each do |user| %>
  <div class="column is-one-quarter">
    <div class="card">
      <% if user.avatar.attached? %>
      <%= image_tag(user.avatar) %>
      <% end %>
      <header class="card-header">
        <p class="card-header-title is-size-6"> Trainee number : <%= user.id%></p>
      </header>
      <div class="card-content">
        <div class="content">  
          <p><span class = "has-text-weight-bold is-size-8">Name : <%= user.name %> </p></span>
        </div>
      </div>  
     <div class="card-footer">  
      
        <%= link_to 'More', manage_path(user), class: "card-footer-item button is-primary is-small" %>

      </div>
    </div>
  </div>  
 <% end %>
</div>

app/views/manages/new.html.erb
<h1>New Manage</h1>

<%= render 'form', manage: @manage %>

<%= link_to 'Back', manages_path %>

app/views/manages/show.html.erb
<div class="columns mt-6 is-centered">
  <div class="columns is-one-quarter"> 
    <div class="card">
      <header class="card-header">
        <p class="card-header-title is-size-4"> Profile </p>
      </header>
      <div class="card-content">
        <div class="content">  
          <p><span class = "has-text-weight-bold is-size-6">Name : <%= @user.name %></p></span>
          <p><span class = "has-text-weight-bold is-size-6">Plan : <%= @user.plan %></p></span>
          <p><span class = "has-text-weight-bold is-size-6">Height : <%= @user.Height %> cm</p></span>
          <p><span class = "has-text-weight-bold is-size-6">Weight : <%= @user.Weight %> kg</p></span>
        </div>
      </div>  
    <div class="card-footer">  
      <div class="card-footer-item">  
        <%= link_to 'Back', manages_path, class: "button is-primary" %>
      </div>  
      </div>
    </div>
  </div>  
 </div>
</div>

<div class="columns mt-6">
 <% @entries.each do |day, entries| %>
  <div class="column">
    <header class="is-size-4">Entry for <%= day %></header>
    <nav class="level is-mobile">
            <div class="level-item has-text-centered">
              <div>
                <div class="level-item"><p class="subtitle">Total Calories  : </p>
                <p class="subtitle"><%= entries.pluck(:calories).sum %> grams </p></div>
                <div class="level-item"><p class="subtitle">Total Proteins  : </p>
                <p class="subtitle"><%= entries.pluck(:proteins).sum %> grams</p></div>
                <div class="level-item"><p class="subtitle">Total Fats : </p>
                <p class="subtitle"><%= entries.pluck(:fats).sum %> grams</p></div>
              </div>
            </div>
          </nav>
    <% entries.each do |entry| %>
    <div class="card">
      <header class="card-header">
        <p class="card-header-title is-size-6"> Meal </p>
      </header>
      <div class="card-content">
        <div class="content">  
          <p><span class = "has-text-weight-bold is-size-8"><%= entry.calories %> kcal Calories</p></span>
          <p><span class = "has-text-weight-bold is-size-8"><%= entry.proteins %>g Protein</p></span>
          <p><span class = "has-text-weight-bold is-size-8"><%= entry.fats %>g fats</p></span>
        </div>
      </div>  
     <% end %>
    </div>
  </div>  
</div>
 <% end %>