config/routes.rb
Rails.application.routes.draw do
  
  resources :exercises
  resources :manages
  root "home#index"
  
  resource :homes 
  
  resources :entries do
  	collection do
       get :view_all
  	end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_header.html.erb
<%  content_for :title do %>

 Foodlog &ndash; <%= DateTime.now.to_s(:nice_date) %>

<%end%>

<section class="hero is-primary is-small ">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <span class="navbar-burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
          	
            <% if user_signed_in? %>
            <div class="navbar-item">
            <% if !has_role? :admin %>  
            <span class="icon is-large">
               <i class="fas fa-utensils fa-2x"></i>
            </span>
            <%= link_to "Create New Entry", new_entry_path, class: "button is-info" %>
            <% end %>
            </div>
           <div class="navbar-item">
            <span class="icon is-large">
               <i class="fas fa-user-edit fa-2x"></i>
            </span>
            <%= link_to "Edit Profile", edit_user_registration_path, class: "button is-success" %>
           </div>
            <div class="navbar-item">
            <span class="icon is-large">
               <i class="fas fa-sign-out-alt fa-2x"></i>
            </span>
            <%= link_to("Logout", destroy_user_session_path, :method => :delete, class: "button is-danger") %>
            </div>
            <% end %>
          
            <% if !user_signed_in? %>
             <div class="navbar-item">
               <%= link_to("Login", new_user_session_path, class: "button is-primary") %>
             </div>
             <div class="navbar-item">
               <%= link_to("Sign Up", new_user_registration_path, class: "button is-primary") %>
             </div> 
              
             </div>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        <% if !user_signed_in? %>
        Foodlog by Joe Wicks
        <% else %>
        <% if content_for(:title) %>
        Welcome <%if user_signed_in?%>
        <%= current_user.name %><%end%></h1>
        <span class="icon is-large">
          <i class="fas fa-dumbbell fa-2x"></i>
        </span>
        <h2 class="subtitle"><%= yield :title %></h2>
        <% else %>
          Foodlog
        <% end %>
        <% end %>
    </div>
  </div>

 <div class="hero-foot">
    <nav class="tabs">
      <div class="container">
        <ul>

          <li class="has-text-weight-bold is-size-6 has-text-white">
           <%= link_to("Home", root_path) %>
          </li>
          <li class="has-text-weight-bold is-size-6 has-text-white"><a>Exercises</a></li>
          <li class="has-text-weight-bold is-size-6 has-text-white"><a>About Us</a></li>
          <li class="has-text-weight-bold is-size-6 has-text-white"><a>Contact Us</a></li>
          <li class="has-text-weight-bold is-size-6 has-text-white"><a>More</a></li>

        </ul>
      </div>
    </nav>
  </div>
</section>

app/views/shared/_signup.html.erb
<div class="card">
	<div class="card-content">
		<div class="content">
			<h2 class="title">Sign up as a Trainer</h2>

			<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
			<%= render "devise/shared/error_messages", resource: resource %>

			<div class="field">
				<label class="label"> 
					<%= f.label :email %><br />
				</label>
					<%= f.email_field :email, autofocus: true, autocomplete: "email", class: "input" %>
			</div>
			<div class="field">
				<label class="label"> 
					<%= f.label :Dob %><br />
				</label>
					<%= f.date_field :Dob, class: "input" %>
			</div>
			<div class="field">
				<label class="label"> 
					<%= f.label :Height %><br />
				</label>
					<%= f.number_field :Height, placeholder: "in cm", class: "input" %>
			</div>
			<div class="field">
				<label class="label"> 
					<%= f.label :Weight %><br />
				</label>
					<%= f.number_field :Weight, placeholder: "in Kg", class: "input" %>
			</div>
			<div class="field">
				<label class="label"> 
					<%= f.label :password %>
				</label>
					<% if @minimum_password_length %>
					<em>(<%= @minimum_password_length %> characters minimum)</em>
					<% end %><br />
					<%= f.password_field :password, autocomplete: "new-password", class: "input" %>
			</div>

			<div class="field">
				<label class="label"> 
					<%= f.label :password_confirmation %><br />
				</label>
                <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "input" %>
			</div>
			<div class="actions">
				<%= f.submit "Sign up", class: "button is-success is-outlined"  %>
			</div>
			<% end %>
    </div>
  </div>
</div>